import { ThemeConfig } from "antd";

// https://ant-design.antgroup.com/theme-editor-cn#component-color
export const 暗色主题: ThemeConfig = {
  token: {
    colorInfo: "#b57e7e",
    colorSuccess: "#a1c191",
    colorWarning: "#ca9b3d",
    borderRadius: 10,
    sizeStep: 4,
    wireframe: true,
  },
  components: {
    Alert: {
      algorithm: true,
      colorBgContainer: "var(--b3-theme-surface)",
      colorBgBase: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    App: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorError: "var(--b3-theme-error)",
      colorPrimary: "var(--b3-theme-primary)",
      colorSuccess: "var(--b3-theme-success)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Badge: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Button: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorError: "var(--b3-theme-error)",
      colorPrimary: "var(--b3-theme-primary)",
      colorSuccess: "var(--b3-theme-success)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
      controlOutline:
        "1px solid rgb(from var(--b3-theme-on-background) r g b/0.2)",
      defaultHoverBg: "var(--b3-list-hover)",
    },
    Calendar: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Card: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Cascader: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Checkbox: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Collapse: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Dropdown: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Form: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
      labelColor: "var(--b3-theme-on-surface)",
    },
    Input: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    InputNumber: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Layout: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
      headerBg: "var(--b3-theme-surface)",
      siderBg: "var(--b3-theme-surface)",
      footerBg: "var(--b3-theme-surface)",
      bodyBg: "var(--b3-theme-surface)",
    },
    Menu: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
      itemBg: "var(--b3-theme-surface)",
      itemHoverBg: "var(--b3-list-hover)",
    },
    Message: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Modal: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Pagination: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Select: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Table: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Tabs: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
      itemActiveColor: "var(--b3-list-hover)",
      itemSelectedColor: "var(--b3-list-hover)",
    },
    Tag: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorPrimary: "var(--b3-theme-primary)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
    Tooltip: {
      algorithm: true,
      colorBgBase: "var(--b3-theme-surface)",
      colorBgContainer: "var(--b3-theme-surface)",
      colorText: "var(--b3-theme-on-background)",
      colorTextBase: "var(--b3-theme-on-background)",
    },
  },
};
